[package]
name = "safe-pkgs-check-staleness"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
semver.workspace = true
safe-pkgs-core = { path = "../../core" }

[dev-dependencies]
tokio.workspace = true

